# food_database.py
# Local list of real product names/brands standing in for a real connected
# food database. Streamlit's selectbox filters this list as you type.

FOOD_DATABASE = [
    "3 Musketeers Original Bar",
    "7 Up Diet",
    "7 Up Original",
    "A&W Root Beer",
    "Airheads Blue Raspberry",
    "Airheads Original",
    "Almond Joy Original Bar",
    "Annie's Gluten Free Mac & Cheese",
    "Annie's Homegrown Fruit Snacks",
    "Annie's Organic Bunny Grahams",
    "Arizona Green Tea with Ginseng & Honey",
    "Arizona Iced Tea with Lemon",
    "Bagel Bites Cheese & Pepperoni Pizza Snacks",
    "Banza Chickpea Pasta Penne",
    "Banza Chickpea Pasta Rotini",
    "Barilla Classic Penne",
    "Barilla Classic Spaghetti",
    "Barilla Gluten Free Penne Pasta",
    "Belvita Blueberry Breakfast Biscuits",
    "Belvita Cinnamon Brown Sugar Biscuits",
    "Ben & Jerry's Cherry Garcia",
    "Ben & Jerry's Chocolate Chip Cookie Dough",
    "Ben & Jerry's Half Baked",
    "Betty Crocker Chocolate Cake Mix",
    "Betty Crocker Chocolate Chip Cookie Mix",
    "Bob's Red Mill Gluten Free 1-to-1 Baking Flour",
    "Bob's Red Mill Gluten Free All Purpose Flour",
    "Bob's Red Mill Gluten Free Rolled Oats",
    "Breyers Mint Chocolate Chip",
    "Breyers Natural Vanilla",
    "Bugles Nacho Cheese",
    "Bugles Original",
    "Butterfinger Original Bar",
    "Campbell's Chicken Noodle Soup",
    "Campbell's Cream of Mushroom Soup",
    "Campbell's Tomato Soup",
    "Canyon Bakehouse Gluten Free Mountain White Bread",
    "Canyon Bakehouse Gluten Free Whole Grain Bread",
    "Cap'n Crunch Crunch Berries",
    "Cap'n Crunch Original",
    "Cap'n Crunch Peanut Butter",
    "Cape Cod Original Kettle Chips",
    "Cape Cod Sea Salt & Vinegar Kettle Chips",
    "Cheerios Apple Cinnamon",
    "Cheerios Frosted",
    "Cheerios Honey Nut",
    "Cheerios Multi Grain",
    "Cheerios Original",
    "Cheetos Baked Crunchy",
    "Cheetos Cheddar Jalapeno",
    "Cheetos Crunchy",
    "Cheetos Crunchy XXTRA Flamin' Hot",
    "Cheetos Flamin' Hot Crunchy",
    "Cheetos Flamin' Hot Puffs",
    "Cheetos Puffs",
    "Cheez-It Extra Toasty",
    "Cheez-It Grooves Sharp Cheddar",
    "Cheez-It Original",
    "Cheez-It White Cheddar",
    "Chex Chocolate Chex",
    "Chex Corn Chex",
    "Chex Rice Chex",
    "Chex Wheat Chex",
    "Chick-fil-A Chicken Sandwich (Restaurant)",
    "Chick-fil-A Waffle Fries (Restaurant)",
    "Chipotle Chicken Burrito Bowl (Restaurant)",
    "Chipotle Steak Burrito (Restaurant)",
    "Chips Ahoy! Chewy",
    "Chips Ahoy! Chunky",
    "Chips Ahoy! Original",
    "Chips Ahoy! Reduced Fat",
    "Chobani Plain Greek Yogurt",
    "Chobani Strawberry on the Bottom",
    "Chobani Vanilla Greek Yogurt",
    "Cinnamon Toast Crunch Original",
    "Clif Bar Chocolate Chip",
    "Clif Bar Crunchy Peanut Butter",
    "Clif Bar White Chocolate Macadamia Nut",
    "Club Original Crackers",
    "Coca-Cola Cherry",
    "Coca-Cola Diet Coke",
    "Coca-Cola Original",
    "Coca-Cola Vanilla",
    "Coca-Cola Zero Sugar",
    "Cocoa Puffs Original",
    "Combos Buffalo Blue Cheese Pretzel",
    "Combos Cheddar Cheese Pretzel",
    "Combos Pizzeria Pretzel",
    "Corn Flakes Kellogg's Original",
    "Dannon Fruit on the Bottom Strawberry",
    "Dannon Oikos Greek Yogurt Vanilla",
    "DiGiorno Four Cheese Pizza",
    "DiGiorno Rising Crust Pepperoni Pizza",
    "Doritos Blaze",
    "Doritos Cool Ranch",
    "Doritos Flamin' Hot",
    "Doritos Nacho Cheese",
    "Doritos Salsa Verde",
    "Doritos Spicy Sweet Chili",
    "Doritos Sweet Chili Heat",
    "Dr Pepper Diet",
    "Dr Pepper Original",
    "Duncan Hines Chocolate Fudge Frosting",
    "Duncan Hines Classic Yellow Cake Mix",
    "Eggo Buttermilk Waffles",
    "Eggo Chocolate Chip Waffles",
    "Eggo Homestyle Waffles",
    "Enjoy Life Gluten Free Chocolate Chips",
    "Enjoy Life Gluten Free Soft Baked Cookies",
    "Fage Total 0% Greek Yogurt",
    "Fage Total 2% Greek Yogurt",
    "Famous Amos Chocolate Chip Cookies",
    "Fanta Grape",
    "Fanta Orange",
    "Fanta Strawberry",
    "Fritos Chili Cheese Corn Chips",
    "Fritos Original Corn Chips",
    "Fritos Scoops",
    "Froot Loops Original",
    "Frosted Flakes Original",
    "Gatorade Cool Blue",
    "Gatorade Fruit Punch",
    "Gatorade Glacier Freeze",
    "Gatorade Lemon-Lime",
    "Gatorade Orange",
    "Girl Scout Samoas",
    "Girl Scout Tagalongs",
    "Girl Scout Thin Mints",
    "Glutino Gluten Free Chocolate Vanilla Creme Cookies",
    "Glutino Gluten Free Pretzels",
    "Goldfish Cheddar",
    "Goldfish Flavor Blasted Xtra Cheddar",
    "Goldfish Pretzel",
    "Grape-Nuts Original",
    "Haagen-Dazs Chocolate",
    "Haagen-Dazs Strawberry",
    "Haagen-Dazs Vanilla",
    "Heinz Sweet Relish",
    "Heinz Tomato Ketchup",
    "Heinz Yellow Mustard",
    "Hellmann's Light Mayonnaise",
    "Hellmann's Real Mayonnaise",
    "Hershey's Cookies 'n' Creme Bar",
    "Hershey's Kisses",
    "Hershey's Milk Chocolate Bar",
    "Hershey's Special Dark",
    "Hidden Valley Original Ranch Dressing",
    "Hidden Valley Ranch Dip Mix",
    "Honey Bunches of Oats Honey Roasted",
    "Honey Bunches of Oats Original",
    "Honey Bunches of Oats with Almonds",
    "Honey Maid Cinnamon Graham Crackers",
    "Honey Maid Honey Graham Crackers",
    "Hostess Cupcakes Chocolate",
    "Hostess Ding Dongs",
    "Hostess Twinkies",
    "Hot Pockets Ham & Cheese",
    "Hot Pockets Meatballs & Mozzarella",
    "Hot Pockets Pepperoni Pizza",
    "Jolly Rancher Gummies",
    "Jolly Rancher Hard Candy Original",
    "Junior Mints Original",
    "KIND Dark Chocolate Nuts & Sea Salt Bar",
    "KIND Fruit and Nut Bar",
    "KIND Peanut Butter Dark Chocolate Bar",
    "Kashi Go Original",
    "Kashi Heart to Heart",
    "Keebler Chips Deluxe Cookies",
    "Keebler Club Crackers",
    "Keebler Fudge Stripes Cookies",
    "Kettle Brand Backyard Barbeque",
    "Kettle Brand Jalapeno",
    "Kettle Brand Salt & Fresh Ground Pepper",
    "Kettle Brand Sea Salt",
    "King Arthur Gluten Free All-Purpose Flour",
    "King Arthur Gluten Free Measure for Measure Flour",
    "Kit Kat Dark Chocolate",
    "Kit Kat Original Bar",
    "Kit Kat White Chocolate",
    "Klondike Original Bar",
    "Kraft Mac & Cheese Original",
    "Kraft Ranch Dressing",
    "Kraft Singles American Cheese",
    "Laffy Taffy Banana",
    "Laffy Taffy Strawberry",
    "Land O'Lakes American Cheese Slices",
    "Land O'Lakes Butter Original",
    "Lay's Barbecue Potato Chips",
    "Lay's Classic Potato Chips",
    "Lay's Dill Pickle Potato Chips",
    "Lay's Flamin' Hot Potato Chips",
    "Lay's Kettle Cooked Original",
    "Lay's Limon Potato Chips",
    "Lay's Salt & Vinegar Potato Chips",
    "Lay's Sour Cream & Onion Potato Chips",
    "Lay's Wavy Original Potato Chips",
    "Lean Cuisine Butternut Squash Ravioli",
    "Lean Cuisine Chicken Fettuccini",
    "Life Cereal Cinnamon",
    "Life Cereal Original",
    "Life Savers Five Flavor",
    "Little Debbie Nutty Buddy Bars",
    "Little Debbie Oatmeal Creme Pies",
    "Little Debbie Swiss Rolls",
    "Lucky Charms Original",
    "M&M's Almond",
    "M&M's Crunchy Cookie",
    "M&M's Milk Chocolate",
    "M&M's Peanut",
    "M&M's Peanut Butter",
    "M&M's Pretzel",
    "Marie Callender's Chicken Pot Pie",
    "Marie Callender's Cornbread",
    "McDonald's Big Mac (Restaurant)",
    "McDonald's Chicken McNuggets (Restaurant)",
    "McDonald's French Fries (Restaurant)",
    "Milky Way Midnight Bar",
    "Milky Way Original Bar",
    "Minute Rice Brown Rice",
    "Minute Rice White Rice",
    "Monster Original Energy",
    "Monster Ultra Zero",
    "Mounds Original Bar",
    "Mountain Dew Baja Blast",
    "Mountain Dew Code Red",
    "Mountain Dew Diet",
    "Mountain Dew Original",
    "Nature Valley Oats 'n Honey Granola Bar",
    "Nature Valley Peanut Butter Granola Bar",
    "Nature Valley Sweet & Salty Nut Bar",
    "Nerds Original",
    "Nilla Wafers",
    "Nutri-Grain Blueberry Bar",
    "Nutri-Grain Strawberry Bar",
    "Nutter Butter Bites",
    "Nutter Butter Original Sandwich Cookies",
    "Ocean Spray Craisins Dried Cranberries",
    "Ocean Spray Cranberry Juice Cocktail",
    "Oreo Birthday Cake",
    "Oreo Double Stuf",
    "Oreo Golden",
    "Oreo Mint",
    "Oreo Original",
    "Oreo Peanut Butter",
    "Oreo Thins Original",
    "Panera Broccoli Cheddar Soup (Restaurant)",
    "Panera Grilled Cheese Sandwich (Restaurant)",
    "Pepperidge Farm Chessmen Butter Cookies",
    "Pepperidge Farm Goldfish Cheddar",
    "Pepperidge Farm Milano Cookies",
    "Pepsi Diet Pepsi",
    "Pepsi Original",
    "Pepsi Wild Cherry",
    "Pepsi Zero Sugar",
    "Philadelphia Original Cream Cheese",
    "Philadelphia Strawberry Cream Cheese",
    "Pillsbury Chocolate Chip Cookie Dough",
    "Pillsbury Grands! Buttermilk Biscuits",
    "Pop-Tarts Frosted Brown Sugar Cinnamon",
    "Pop-Tarts Frosted Chocolate Fudge",
    "Pop-Tarts Frosted Strawberry",
    "Pop-Tarts S'mores",
    "Popchips BBQ",
    "Popchips Sea Salt",
    "Popchips Sour Cream & Onion",
    "Popsicle Original Rainbow Pops",
    "Powerade Fruit Punch",
    "Powerade Mountain Berry Blast",
    "Prego Alfredo Sauce",
    "Prego Traditional Pasta Sauce",
    "Pringles BBQ",
    "Pringles Cheddar Cheese",
    "Pringles Original",
    "Pringles Pizza",
    "Pringles Ranch",
    "Pringles Screamin' Dill Pickle",
    "Pringles Sour Cream & Onion",
    "Progresso Chicken Noodle Soup",
    "Progresso Minestrone Soup",
    "Quaker Chewy Granola Bar Chocolate Chip",
    "Quaker Instant Oatmeal Maple & Brown Sugar",
    "Quaker Old Fashioned Oats",
    "Quaker Rice Cakes Lightly Salted",
    "RXBar Blueberry",
    "RXBar Chocolate Sea Salt",
    "RXBar Peanut Butter",
    "Ragu Cheese Creations Alfredo",
    "Ragu Old World Style Traditional Sauce",
    "Raisin Bran Kellogg's Original",
    "Red Bull Original",
    "Red Bull Sugarfree",
    "Reese's Peanut Butter Cups",
    "Reese's Peanut Butter Cups Minis",
    "Reese's Pieces",
    "Reese's Puffs Original",
    "Rice Krispies Original",
    "Rice Krispies Treats Original Bars",
    "Rice-A-Roni Chicken Flavor",
    "Rice-A-Roni Fried Rice",
    "Ritz Cheese Sandwich Crackers",
    "Ritz Original Crackers",
    "Ritz Toasted Chips Sour Cream & Onion",
    "Ruffles Cheddar & Sour Cream",
    "Ruffles Flamin' Hot",
    "Ruffles Original",
    "Runts Original",
    "Sargento Sharp Cheddar Slices",
    "Sargento Shredded Mozzarella",
    "Schar Gluten Free Breadsticks",
    "Schar Gluten Free Classic White Bread",
    "Schar Gluten Free Table Crackers",
    "Simple Mills Gluten Free Almond Flour Crackers",
    "Simple Mills Gluten Free Chocolate Chip Cookies",
    "Skittles Original",
    "Skittles Sour",
    "Skittles Tropical",
    "Skittles Wild Berry",
    "Snapple Apple",
    "Snapple Lemon Tea",
    "Snapple Peach Tea",
    "Snickers Almond Bar",
    "Snickers Minis",
    "Snickers Original Bar",
    "Snickers Peanut Butter Bar",
    "Snyder's of Hanover Braided Twists",
    "Snyder's of Hanover Honey Mustard & Onion Pretzel Pieces",
    "Snyder's of Hanover Original Pretzels",
    "Sour Patch Kids Original",
    "Special K Original",
    "Special K Red Berries",
    "Sprite Original",
    "Sprite Zero Sugar",
    "Stacy's Cinnamon Sugar Pita Chips",
    "Stacy's Parmesan Garlic & Herb Pita Chips",
    "Stacy's Simply Naked Pita Chips",
    "Starbucks Frappuccino Mocha",
    "Starbucks Iced Coffee",
    "Starbucks Restaurant Blueberry Muffin (Restaurant)",
    "Starbucks Restaurant Vanilla Latte (Restaurant)",
    "Starburst Original Fruit Chews",
    "Starburst Sour",
    "Stouffer's Lasagna with Meat Sauce",
    "Stouffer's Mac & Cheese",
    "Subway Meatball Marinara Sandwich (Restaurant)",
    "Subway Turkey Sandwich (Restaurant)",
    "Sun Chips French Onion",
    "Sun Chips Harvest Cheddar",
    "Sun Chips Original",
    "Terra Original Vegetable Chips",
    "Terra Sweet Potato Chips",
    "Tostitos Hint of Lime",
    "Tostitos Original Tortilla Chips",
    "Tostitos Restaurant Style",
    "Tostitos Scoops",
    "Totino's Party Pizza Cheese",
    "Totino's Pizza Rolls Pepperoni",
    "Trader Joe's Cauliflower Gnocchi",
    "Trader Joe's Everything but the Bagel Seasoning",
    "Triscuit Cracked Pepper & Olive Oil",
    "Triscuit Fire Roasted Tomato",
    "Triscuit Original",
    "Twix Caramel Bar",
    "Twix Minis",
    "Twix Peanut Butter Bar",
    "Twizzlers Pull 'n' Peel",
    "Twizzlers Strawberry Twists",
    "Udi's Gluten Free Bagels",
    "Udi's Gluten Free White Sandwich Bread",
    "Udi's Gluten Free Whole Grain Bread",
    "Uncle Ben's Original Long Grain Rice",
    "Uncle Ben's Ready Rice Whole Grain Brown",
    "Utz Crab Chips",
    "Utz Original Pretzels",
    "Utz Sour Cream & Onion",
    "Vitaminwater XXX Acai-Blueberry-Pomegranate",
    "Vitaminwater Zero Rise",
    "Welch's Fruit Snacks Mixed Fruit",
    "Welch's Grape Jelly",
    "Wheat Thins Original",
    "Wheat Thins Ranch",
    "Wheat Thins Sundried Tomato & Basil",
    "Whoppers Original",
    "Yoplait Light Yogurt Vanilla",
    "Yoplait Original Strawberry Yogurt",
]
